import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                brand: {
                    blue: '#2f5fdb',
                    indigo: '#4338ca',
                    steel: '#3f6db3',
                    dark: '#1e3a8a',
                    red: '#e05237',
                    green: '#5eab35',
                    yellow: '#f5b52e',
                },
                // English learning module (Material 3 style tokens, ported from laravel-study-function)
                'inverse-surface': '#3d2d27',
                'tertiary-container': '#0078c7',
                'tertiary-fixed': '#d1e4ff',
                'on-tertiary-fixed-variant': '#00497c',
                'surface-container-lowest': '#ffffff',
                outline: '#8e7166',
                'on-primary-fixed-variant': '#7f2b00',
                'on-tertiary-container': '#fdfcff',
                tertiary: '#005f9f',
                'primary-container': '#cc4900',
                'on-surface-variant': '#5a4138',
                'on-error': '#ffffff',
                'secondary-fixed-dim': '#d9c2b8',
                'on-surface': '#261813',
                'outline-variant': '#e2bfb3',
                'on-primary-fixed': '#370e00',
                'on-error-container': '#93000a',
                'on-primary': '#ffffff',
                secondary: '#6c5b53',
                'on-primary-container': '#fffbff',
                'error-container': '#ffdad6',
                'surface-container-high': '#fde3d9',
                'secondary-fixed': '#f6ded3',
                'primary-fixed': '#ffdbce',
                'on-secondary-fixed': '#251913',
                surface: '#fff8f6',
                'primary-fixed-dim': '#ffb599',
                'surface-dim': '#efd5cc',
                'inverse-on-surface': '#ffede7',
                'on-secondary': '#ffffff',
                'on-background': '#261813',
                'surface-variant': '#f8ddd4',
                'surface-container': '#ffe9e2',
                primary: '#a33900',
                'on-secondary-fixed-variant': '#53433c',
                'tertiary-fixed-dim': '#9ecaff',
                'on-tertiary-fixed': '#001d36',
                'surface-bright': '#fff8f6',
                error: '#ba1a1a',
                'inverse-primary': '#ffb599',
                'on-secondary-container': '#726159',
                background: '#fff8f6',
                'on-tertiary': '#ffffff',
                'secondary-container': '#f6ded3',
                'surface-tint': '#a73a00',
                'surface-container-low': '#fff1ec',
                'surface-container-highest': '#f8ddd4',
            },
            fontFamily: {
                sans: ['"Noto Sans JP"', ...defaultTheme.fontFamily.sans],
                display: ['"Poppins"', '"Noto Sans JP"', ...defaultTheme.fontFamily.sans],
                // English learning module (does not override the "display" key above)
                'headline-md': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                'body-md': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                caption: ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                'headline-lg': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                'headline-lg-mobile': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                'label-md': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
                'body-lg': ['"Public Sans"', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                // English learning module
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
                display: ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
            },
            maxWidth: {
                'container-max': '1280px',
            },
            spacing: {
                'margin-mobile': '16px',
                'margin-desktop': '40px',
            },
            boxShadow: {
                card: '0 12px 32px -12px rgba(30, 58, 138, 0.22)',
                'card-hover': '0 20px 44px -12px rgba(30, 58, 138, 0.30)',
                soft: '0 2px 12px rgba(30, 58, 138, 0.08)',
            },
        },
    },

    plugins: [forms],
};
